### ISSUE TITLE
GDB stub causes boot failure

### ISSUE THREAD

**Issue by linden** [saagarjha/VirtualApple#3]
Currently when attempting to boot with GDB stub enabled it causes the VM to fail, without it enabled it boots fine.

Full configuration.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/70739041/155685952-8898d65a-8d4e-40e0-8943-7ad1c925c745.png">

Error message.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/70739041/155685896-cc2afcc1-6dc3-4eb3-a2ac-be7a6526d882.png">

P.S. great project, thanks for building it!

**Comment by saagarjha** [comment]
That error indicates that the virtual machine service is crashing. Are you seeing reports for com.apple.Virtualization.VirtualMachine talking about restricted devices? If so, your entitlement check bypass is probably not working correctly.

**Comment by linden** [comment]
Bingo, just checked and found `FATAL: Unable to create a virtual machine with restricted devices`.

Haven't heard of a entitlement check bypass before so that's probably the issue, would something like [osy/AMFIExemption](https://github.com/osy/AMFIExemption) do the trick?

**Comment by saagarjha** [comment]
You're going to have to turn off SIP either way, so I recommend doing that first. Once you've done that, you have a number of options: you can turn off entitlement enforcement altogether with the `amfi_get_out_of_my_way` boot argument, or do something more selective. Personally, I point [my library_injector tool](https://gist.github.com/saagarjha/a70d44951cb72f82efee3317d80ac07f) at the service and load this into it:

```c
#import <xpc/xpc.h>

xpc_object_t xpc_connection_copy_entitlement_value(xpc_connection_t, const char *);

xpc_object_t overridden_xpc_connection_copy_entitlement_value(xpc_connection_t connection, const char *entitlement) {
	return xpc_bool_create(true);
}

__attribute__((used, section("__DATA,__interpose"))) static struct {
	xpc_object_t (*overridden_xpc_connection_copy_entitlement_value)(xpc_connection_t, const char *);
	xpc_object_t (*xpc_connection_copy_entitlement_value)(xpc_connection_t, const char *);
} xpc_connection_copy_entitlement_value_overrides[] = {
    {overridden_xpc_connection_copy_entitlement_value, xpc_connection_copy_entitlement_value},
};
```

osy's tool also seems fine to me, but I can double-check with them to see if it would be useful here.

**Comment by linden** [comment]
Thanks for the detailed reply. 

I've decided to go with `library_injector` as it seems like the safer option but I'm having some difficulty.

Here's a step-by-step of what I've done so far.
1. booted into recovery.
2. disabled SIP.
```sh
csrutil disable
```
3. compiled `library_injector`.
```sh
clang++ -arch x86_64 -arch arm64 -std=c++20 library_injector.cpp -lbsm -lEndpointSecurity -o library_injector
```
4. wrapped the executable into a .app with my [wrap](https://github.com/linden/wrap) tool (which bundles and signs it).
```sh
wrap -ID="redacted@email.com" -bundle=signer -origin=linden -path=library_injector
```
6. attempted to add the entitlement (probably where it went wrong).
```sh
codesign -d --entitlements entitlements.xml ./signer.app
```
`entitlements.xml` contains the following.
```xml
<plist version="1.0">
<dict>
    <key>application-identifier</key>
    <string>com.linden.example</string>
    <key>aps-environment</key>
    <string>production</string>
    <key>com.apple.developer.endpoint-security.client</key>
    <true/>
</dict>
</plist>
```
7. compiled the library to be injected.
```sh
clang++ -arch arm64 -std=c++20 injected.cpp -c
```
8. attempted to inject the library into the binary.
```sh
./signer.app/Contents/MacOS/signer ./inject.o ~/Applications/VirtualApple.app/Contents/MacOS/VirtualApple
```
got the following error message.
```sh
linden@lindens-mbp library_injector % ./signer.app/Contents/MacOS/signer /Users/linden/Documents/apps/misc/library_injector/inject.o /Users/linden/Documents/apps/misc/library_injector/inject.o 
libc++abi: terminating with uncaught exception of type std::runtime_error: Check "es_new_client(&client, ^(es_client_t *client, const es_message_t *message) { switch (message->event_type) { case ES_EVENT_TYPE_AUTH_EXEC: { const char *name = message->event.exec.target->executable->path.data; for (const auto &process : processes) { if (std::strstr(name, process)) { pid_t pid = audit_token_to_pid(message->process->audit_token); ptrace(PT_ATTACHEXC, pid, nullptr, 0); ptrace(PT_DETACH, pid, nullptr, 0); inject(pid, library); } } es_respond_auth_result(client, message, ES_AUTH_RESULT_ALLOW, false); break; } default: ensure(false && "Unexpected event type!"); } }) == ES_NEW_CLIENT_RESULT_SUCCESS" failed at library_injector.cpp:252 in function main
zsh: abort      ./signer.app/Contents/MacOS/signer
```

**Comment by saagarjha** [comment]
There are multiple ways to use those tools, but there are important to note:

1. Apple's tooling is compiled as arm64e, so you will need to build for that architecture for both library_injector and the injected library. This means both compile commands will need `-arch arm64e` in them, and you will also need to add `-arm64e_preview_abi` to your boot arguments using `nvram boot-args` (and reboot).
2. Signing the library_injector tool does not require an identity (it can just be ad-hoc) but it does require the com.apple.developer.endpoint-security.client entitlement (I am not sure if the other ones would affect the outcome, but I would just avoid them if you don't have a pressing need for them).
3. The injected code needs to be compiled as a dynamic library.
4. The library_injector tool needs to run as root and target Apple's XPC service.

Putting it all together, I think these commands should give you an idea of how to make this work:

```console
$ clang++ -arch arm64e -std=c++20 library_injector.cpp -lbsm -lEndpointSecurity -o library_injector
$ codesign -s - --entitlements library_injector_entitlements.plist library_injector
$ clang enable_debugging.c -arch arm64e -shared -o libenable_debugging.dylib
$ sudo ./library_injector libenable_debugging.dylib com.apple.Virtualization.VirtualMachine
```

**Comment by linden** [comment]
Awesome, got it all working now. Thanks.
*Note to anyone else trying this in the future: don't forget to write out the full path to your dylib.*

Unrelated to the issue at hand but is it possible to modify the serial number of the VM? I'm looking to reverse engineer Private Relay (since it seems nobody else has) but I can't access any Apple service that requires an Apple ID.

**Comment by saagarjha** [comment]
Virtualization does not support signing in with an Apple ID, unfortunately.

**Comment by linden** [comment]
That's unfortunate, well that's my issue solved. Thanks again!

**Comment by pwnee** [comment]
Is the `library_injector` technique still valid? I'm trying on host&guest Ventura 13.5 and getting
<img width="275" alt="image" src="https://github.com/saagarjha/VirtualApple/assets/93780947/d683f353-efae-433f-a9ea-94982cd60bde">

some logs:
```
default	19:37:11.276876+0300	kernel	com.apple.Virtualization.Virtual[1378] Corpse allowed 1 of 5
debug	19:37:11.277808+0300	VirtualApple	found no value for key cursorIsCustomized in CFPrefsSearchListSource<0x600000b7d780> (Domain: com.apple.universalaccess, Container: (null))
debug	19:37:11.277955+0300	VirtualApple	Bundle: CFBundle 0x600001c40460 </System/Library/Frameworks/Virtualization.framework> (framework, loaded), key: The virtual machine failed to start., value: (null), table: Localizable, localizationNames: (null), result: The virtual machine failed to start.
debug	19:37:11.277987+0300	VirtualApple	Bundle: CFBundle 0x600001c40460 </System/Library/Frameworks/Virtualization.framework> (framework, loaded), key: Internal Virtualization error., value: (null), table: Localizable, localizationNames: (null), result: Internal Virtualization error.
```

**Comment by arm64eabi** [comment]
@saagarjha your library_injector method seems to be broken in macOS 14.4 hosts; the injector process gets killed upon the launch of the vm.

**Comment by saagarjha** [comment]
Can you post a crash log?

**Comment by arm64eabi** [comment]
here they are
[ips.zip](https://github.com/saagarjha/VirtualApple/files/14600179/ips.zip)

**Comment by saagarjha** [comment]
I think I need to look into this more, because I can only reproduce this on one of my machines…
